name: Build Score Data Extractor

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      baseDir: ./DataExtractor
      artifactDir: ${{env.baseDir}}/bin/${{matrix.buildplatform}}/${{matrix.buildconfig}}
      solutionName: ScoreDataExtractor.sln
      artifactName: CompileScore-Extractor-${{matrix.buildplatform}}-${{matrix.buildconfig}}
    
    strategy:
      matrix:
        buildconfig: [Debug, Release]
        buildplatform: [x86, x64]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
     
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
        
    - name: NuGet restore 
      working-directory: ${{env.baseDir}}
      run: nuget restore ${{ env.solutionName }}
     
    - name: Build Score Data Extractor
      working-directory: ${{env.baseDir}}
      run: msbuild /m /p:Configuration=${{matrix.buildconfig}} /p:Platform=${{matrix.buildplatform}} ${{ env.solutionName }}
      
    - name: Upload Artifacts 1
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.artifactName}}
        path: ${{env.artifactDir}}/*.exe  
        
    - name: Upload Artifacts 2
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.artifactName}}
        path: ${{env.artifactDir}}/*.dll  
